// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class BeaconData (
  val serviceUUID: String? = null,
  val hwid: String? = null,
  val rssi: Double? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BeaconData {
      val serviceUUID = list[0] as String?
      val hwid = list[1] as String?
      val rssi = list[2] as Double?
      return BeaconData(serviceUUID, hwid, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      serviceUUID,
      hwid,
      rssi,
    )
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BeaconManagerApi {
  fun setBeaconServiceUUIDs(uuid: List<String>, callback: (Result<Unit>) -> Unit)
  fun startScan(callback: (Result<Unit>) -> Unit)
  fun stopScan(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BeaconManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      StandardMessageCodec()
    }
    /** Sets up an instance of `BeaconManagerApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: BeaconManagerApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.beacon_plugin.BeaconManagerApi.setBeaconServiceUUIDs", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uuidArg = args[0] as List<String>
            api.setBeaconServiceUUIDs(uuidArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.beacon_plugin.BeaconManagerApi.startScan", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startScan() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.beacon_plugin.BeaconManagerApi.stopScan", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopScan() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object FlutterBeaconApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BeaconData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BeaconData -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class FlutterBeaconApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by FlutterBeaconApi. */
    val codec: MessageCodec<Any?> by lazy {
      FlutterBeaconApiCodec
    }
  }
  fun onScanned(beaconDataListArg: List<BeaconData>, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.beacon_plugin.FlutterBeaconApi.onScanned", codec)
    channel.send(listOf(beaconDataListArg)) {
      callback()
    }
  }
}
