// Autogenerated from Pigeon (v10.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class BeaconData (
  val uuid: String? = null,
  val major: String? = null,
  val minor: String? = null,
  val rssi: Long? = null,
  val proximity: Long? = null,
  val hwid: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BeaconData {
      val uuid = list[0] as String?
      val major = list[1] as String?
      val minor = list[2] as String?
      val rssi = list[3].let { if (it is Int) it.toLong() else it as Long? }
      val proximity = list[4].let { if (it is Int) it.toLong() else it as Long? }
      val hwid = list[5] as String?
      return BeaconData(uuid, major, minor, rssi, proximity, hwid)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      uuid,
      major,
      minor,
      rssi,
      proximity,
      hwid,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RegionData (
  val uuid: String? = null,
  val major: String? = null,
  val minor: String? = null,
  val state: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RegionData {
      val uuid = list[0] as String?
      val major = list[1] as String?
      val minor = list[2] as String?
      val state = list[3].let { if (it is Int) it.toLong() else it as Long? }
      return RegionData(uuid, major, minor, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      uuid,
      major,
      minor,
      state,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object BeaconManagerApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BeaconData.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegionData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BeaconData -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is RegionData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BeaconManagerApi {
  fun startMonitoring(callback: (Result<Unit>) -> Unit)
  fun stopMonitoring(callback: (Result<Unit>) -> Unit)
  fun getMonitoredRegion(callback: (Result<RegionData?>) -> Unit)
  fun startRanging(callback: (Result<Unit>) -> Unit)
  fun stopRanging(callback: (Result<Unit>) -> Unit)
  fun getRangedBeacons(callback: (Result<List<BeaconData?>?>) -> Unit)
  fun startForegroundService(callback: (Result<Unit>) -> Unit)
  fun stopForegroundService(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BeaconManagerApi. */
    val codec: MessageCodec<Any?> by lazy {
      BeaconManagerApiCodec
    }
    /** Sets up an instance of `BeaconManagerApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: BeaconManagerApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.startMonitoring", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startMonitoring() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.stopMonitoring", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopMonitoring() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.getMonitoredRegion", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getMonitoredRegion() { result: Result<RegionData?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.startRanging", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startRanging() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.stopRanging", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRanging() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.getRangedBeacons", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRangedBeacons() { result: Result<List<BeaconData?>?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.startForegroundService", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.startForegroundService() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.BeaconManagerApi.stopForegroundService", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopForegroundService() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
